[build]
  functions = "server"

[build.environment]
  YARN_VERSION = "1.22.17"
  NODE_ENV = "production"
  NETLIFY_USE_YARN = "true"
  YARN_FLAGS = "--production=false"
  YARN_PRODUCTION = "true"

[[redirects]]
  to="/.netlify/server/server/:splat"
  from="/*"
  status=200