[build.environment]
  YARN_VERSION = "1.22.17"
  NODE_ENV = "production"

[dev]
  command = "yarn run dev"
  publish = "dist"
  # We need another port for the application because Vite occupies the 3000.
  port = 8080

[build]
  command = "yarn run build"
  publish = "dist"
