[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  YARN_VERSION = "1.22.17"
  NODE_ENV = "production"
  NETLIFY_USE_YARN = "true"
  YARN_FLAGS = "--production=false"